# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build all modules

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test minecraft mod
        run: ./gradlew test
        working-directory: modded-minecraft
      - name: Setup Buildx
        id: buildx
        uses:
          docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./modded-minecraft
          provenance: false
          file: ./modded-minecraft/Dockerfile
          push: false
          tags: |
            minecraft-server:latest
      - name: Build extension
        run: mvn install -DskipTests=true
        working-directory: extension
      - name: Build todo app
        run: mvn install  -DskipTests=true
        working-directory: quarkus-todo-app
      - uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          output_file_paths: '[./demo-script.md]'
